version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: homeio
      POSTGRES_PASSWORD: homeio
      POSTGRES_DB: homeio

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  web:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - postgres
      - mongo
